#!/usr/bin/env bash


if [ "$#" -lt 5 ]; then
    echo
    echo "Usage: $(basename $0) TEST_FILE PROTOCOL HOST PORT RAMP_UP_SECONDS MIN_USER_COUNT MAX_USER_COUNT STEP_USER_COUNT [LOOP_COUNT]"
    echo
    echo "Default LOOP_COUNT: 1"
    exit 1
fi

clear

RESULTS_DIRECTORY="results"
REPORTS_DIRECTORY="reports"
GRAPHS_DIRECTORY="graphs"

TEST_FILE=$1
PROTOCOL=$2
HOST=$3
PORT=$4
RAMP_UP=$5
MIN_USER_COUNT=$6
MAX_USER_COUNT=$7
STEP_USER_COUNT=$8
LOOP_COUNT=$9

if [ "$MIN_USER_COUNT" -le "0" ]; then
    MIN_USER_COUNT=$STEP_USER_COUNT
fi

if [ -z "$9" ]; then
    LOOP_COUNT=1
fi

for (( USER_COUNT = $MIN_USER_COUNT; USER_COUNT <= $MAX_USER_COUNT; USER_COUNT += STEP_USER_COUNT ))
do

	TEST_NAME="${TEST_FILE##*/}"
	TEST_NAME="${TEST_NAME%.*}"

	OUTPUT_FILE_NAME_ROOT="${TEST_NAME}-${RAMP_UP}s-${USER_COUNT}"

	RESULTS_FILE="${RESULTS_DIRECTORY}/${OUTPUT_FILE_NAME_ROOT}.jtl"
	CURRENT_REPORTS_DIRECTORY="${REPORTS_DIRECTORY}/${OUTPUT_FILE_NAME_ROOT}"

	RESULTS_TREE_FILE="${RESULTS_DIRECTORY}/${OUTPUT_FILE_NAME_ROOT}.csv"

	CURRENT_GRAPHS_DIRECTORY="${GRAPHS_DIRECTORY}/${OUTPUT_FILE_NAME_ROOT}"
	GRAPHS_FILE_PREFIX="${OUTPUT_FILE_NAME_ROOT}-"

	echo
	echo "TEST NAME: ${TEST_NAME}"
	echo $OUTPUT_FILE_NAME_ROOT
	echo "RESULTS FILE: ${RESULTS_FILE}"
	echo "REPORTS DIRECTORY: ${CURRENT_REPORTS_DIRECTORY}"
	echo "TREE VIEW RESULTS FILE: ${RESULTS_TREE_FILE}"
	echo "GRAPHS DIRECTORY: ${CURRENT_GRAPHS_DIRECTORY}"
	echo $GRAPHS_FILE_PREFIX
	echo
	echo "USER COUNT: ${USER_COUNT}"
	echo



	rm $RESULTS_DIRECTORY/$OUTPUT_FILE_NAME_ROOT.* 2>/dev/null
	rm -rf $CURRENT_REPORTS_DIRECTORY
	rm -rf $CURRENT_GRAPHS_DIRECTORY

	apache-jmeter/bin/jmeter \
	-n -t $TEST_FILE \
	-l $RESULTS_FILE \
	-e -o $CURRENT_REPORTS_DIRECTORY \
	-Jprotocol=$PROTOCOL \
	-Jhost=$HOST \
	-Jport=$PORT \
	-Jusers=$USER_COUNT \
	-Jrampup_period=$RAMP_UP \
	-Jloop_count=$LOOP_COUNT \
	-Jresults_tree_file=$RESULTS_TREE_FILE \
	-Jgraphs_results_file=$RESULTS_TREE_FILE \
	-Jgraphs_directory=$CURRENT_GRAPHS_DIRECTORY \
	-Jgraphs_file_prefix=$GRAPHS_FILE_PREFIX

done